### ISSUE TITLE
Org Dropdown on Create New Project needs to be sized correctly 

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-qgis-plugin#190]
In the latest update is it too small and centered. Should be longer and align left

#![image](https://cloud.githubusercontent.com/assets/67992/25684298/6238ee48-3015-11e7-9231-780f469f8cf8.png)

**Comment by dimasciput** [comment]
Fixed on latest PR https://github.com/Cadasta/cadasta-qgis-plugin/pull/192

**Comment by wonderchook** [comment]
@dimasciput still not quite right. Just needs to be moved to align left properly.

![image](https://cloud.githubusercontent.com/assets/67992/25811725/fe2b1504-33c8-11e7-959a-d0fef45f1524.png)

**Comment by cchristelis** [comment]
ping @dimasciput

**Comment by dimasciput** [comment]
Tested in Windows 10 with latest cadasta build :
![qgis](https://user-images.githubusercontent.com/1979569/29000496-e5f35c02-7a96-11e7-990e-e8eb65cd6129.PNG)

**Comment by SteadyCadence** [comment]
Dimas, are you using your machine for that testing or browser stack?

**Comment by dimasciput** [comment]
@SteadyCadence I'm using my machine

**Comment by SteadyCadence** [comment]
I do not have a way to test this.  I'll have to ask the team... I'm not sure what tool we could use to do more testing. Are there any that work with QGIS machines?

**Comment by dimasciput** [comment]
QGIS is works in linux, windows and mac. https://www.qgis.org/en/site/forusers/download.html

**Comment by cchristelis** [comment]
This issue has been solved in other tickets, hence closing.
