### ISSUE TITLE
Password and username seem to be switched in options

### ISSUE THREAD

**Issue by timlinux** [Cadasta/cadasta-qgis-plugin#53]
![screen shot 2016-12-27 at 9 01 23 pm](https://cloud.githubusercontent.com/assets/178003/21506347/20030eba-cc78-11e6-967f-a3a10918d82f.png)

Entering my password in the username and my username in the password does **NOT** test successfully either so I think there is more wrong than just needing to switch the controls around....

I did verify my credentials work on the web site.

Can you also confirm which format the URL is expected to be (an example in the tooltip would be great....

**Comment by meomancer** [comment]
it is fixed in : https://github.com/kartoza/cadasta-qgis-plugin/pull/42
i changed to stacked widget

**Comment by timlinux** [comment]
@meomancer not sure how the stacked widget relates to this dialog? I still can't log in using my credentials though. Can you share what URL you are using to login in with ?

**Comment by meomancer** [comment]
@timlinux it is fixed at #42
i think you can't login because of username input that is have password type is actually for password.
the position was arranged when changing to linear layout

you could use: kartoza.demo/demo.kartoza1! with that https://demo.cadasta.org/
